name: Block Direct Main Branch Push

on:
  push:
    branches:
      - main

jobs:
  block:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if push is not from a PR
        run: |
          echo "Direct push to main is not allowed. Heheee"
          exit 1
